name: film_watchlist
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  riverpod: ^3.0.3
  flutter_riverpod: ^3.0.3
  uuid: ^4.5.2
  http: ^1.6.0
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.3.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
